// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "tchart1.h"

/////////////////////////////////////////////////////////////////////////////
// CTchart1

IMPLEMENT_DYNCREATE(CTchart1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTchart1 properties

/////////////////////////////////////////////////////////////////////////////
// CTchart1 operations
