// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeries;

/////////////////////////////////////////////////////////////////////////////
// CADXFunction wrapper class

class CADXFunction : public COleDispatchDriver
{
public:
	CADXFunction() {}		// Calls COleDispatchDriver default constructor
	CADXFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CADXFunction(const CADXFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CSeries GetDMDown();
	CSeries GetDMUp();
};
