// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAmountFilter wrapper class

class CAmountFilter : public COleDispatchDriver
{
public:
	CAmountFilter() {}		// Calls COleDispatchDriver default constructor
	CAmountFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAmountFilter(const CAmountFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetPercent();
	void SetPercent(BOOL bNewValue);
	long GetAmount();
	void SetAmount(long nNewValue);
};
