// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAverageFunction wrapper class

class CAverageFunction : public COleDispatchDriver
{
public:
	CAverageFunction() {}		// Calls COleDispatchDriver default constructor
	CAverageFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAverageFunction(const CAverageFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIncludeNulls();
	void SetIncludeNulls(BOOL bNewValue);
};
