// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CBevelFilter wrapper class

class CBevelFilter : public COleDispatchDriver
{
public:
	CBevelFilter() {}		// Calls COleDispatchDriver default constructor
	CBevelFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CBevelFilter(const CBevelFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetBright();
	void SetBright(long nNewValue);
	long GetSize();
	void SetSize(long nNewValue);
};
