// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeries;

/////////////////////////////////////////////////////////////////////////////
// CBollingerFunction wrapper class

class CBollingerFunction : public COleDispatchDriver
{
public:
	CBollingerFunction() {}		// Calls COleDispatchDriver default constructor
	CBollingerFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CBollingerFunction(const CBollingerFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetDeviation();
	void SetDeviation(double newValue);
	BOOL GetExponential();
	void SetExponential(BOOL bNewValue);
	CSeries GetLowBand();
};
