#if !defined(AFX_CHARTPAGENAVIGATOR_H__E22C3BFF_0F56_49E1_AE07_AEF7B40C9A22__INCLUDED_)
#define AFX_CHARTPAGENAVIGATOR_H__E22C3BFF_0F56_49E1_AE07_AEF7B40C9A22__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChartPageNavigator wrapper class

class CChartPageNavigator : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChartPageNavigator)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc7f407c, 0xadaa, 0x49de, { 0xa4, 0x97, 0xf0, 0x3c, 0x57, 0x52, 0xae, 0xce } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void EnableButtons();
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTPAGENAVIGATOR_H__E22C3BFF_0F56_49E1_AE07_AEF7B40C9A22__INCLUDED_)
