// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChartFont wrapper class

class CChartFont : public COleDispatchDriver
{
public:
	CChartFont() {}		// Calls COleDispatchDriver default constructor
	CChartFont(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartFont(const CChartFont& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	long GetSize();
	void SetSize(long nNewValue);
	BOOL GetBold();
	void SetBold(BOOL bNewValue);
	BOOL GetItalic();
	void SetItalic(BOOL bNewValue);
	BOOL GetUnderline();
	void SetUnderline(BOOL bNewValue);
	BOOL GetStrikethrough();
	void SetStrikethrough(BOOL bNewValue);
	short GetCharset();
	void SetCharset(short nNewValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	long GetPixelsPerInch();
};
