// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CColorFilter wrapper class

class CColorFilter : public COleDispatchDriver
{
public:
	CColorFilter() {}		// Calls COleDispatchDriver default constructor
	CColorFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CColorFilter(const CColorFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetRed();
	void SetRed(long nNewValue);
	long GetGreen();
	void SetGreen(long nNewValue);
	long GetBlue();
	void SetBlue(long nNewValue);
};
