// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCompressFunction wrapper class

class CCompressFunction : public COleDispatchDriver
{
public:
	CCompressFunction() {}		// Calls COleDispatchDriver default constructor
	CCompressFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCompressFunction(const CCompressFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCompress();
	void SetCompress(long nNewValue);
};
