// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CContrastFilter wrapper class

class CContrastFilter : public COleDispatchDriver
{
public:
	CContrastFilter() {}		// Calls COleDispatchDriver default constructor
	CContrastFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CContrastFilter(const CContrastFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetPercent();
	void SetPercent(BOOL bNewValue);
	long GetAmount();
	void SetAmount(long nNewValue);
};
