// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CContourMarks wrapper class

class CContourMarks : public COleDispatchDriver
{
public:
	CContourMarks() {}		// Calls COleDispatchDriver default constructor
	CContourMarks(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CContourMarks(const CContourMarks& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetAntiOverlap();
	void SetAntiOverlap(BOOL bNewValue);
	BOOL GetAtSegments();
	void SetAtSegments(BOOL bNewValue);
	BOOL GetColorLevel();
	void SetColorLevel(BOOL bNewValue);
	long GetMargin();
	void SetMargin(long nNewValue);
	long GetDensity();
	void SetDensity(long nNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
};
