// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCropFilter wrapper class

class CCropFilter : public COleDispatchDriver
{
public:
	CCropFilter() {}		// Calls COleDispatchDriver default constructor
	CCropFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCropFilter(const CCropFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
};
