// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeries;

/////////////////////////////////////////////////////////////////////////////
// CCustomSeriesList wrapper class

class CCustomSeriesList : public COleDispatchDriver
{
public:
	CCustomSeriesList() {}		// Calls COleDispatchDriver default constructor
	CCustomSeriesList(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCustomSeriesList(const CCustomSeriesList& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void ClearValues();
	long First();
	long Last();
	CSeries GetItems(long Index);
};
