// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "customserieslist.h"

// Dispatch interfaces referenced by this interface
#include "series.h"


/////////////////////////////////////////////////////////////////////////////
// CCustomSeriesList properties

/////////////////////////////////////////////////////////////////////////////
// CCustomSeriesList operations

void CCustomSeriesList::ClearValues()
{
	InvokeHelper(0xc9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CCustomSeriesList::First()
{
	long result;
	InvokeHelper(0xca, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CCustomSeriesList::Last()
{
	long result;
	InvokeHelper(0xcb, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CSeries CCustomSeriesList::GetItems(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcc, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CSeries(pDispatch);
}
