// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDownSamplingFunction wrapper class

class CDownSamplingFunction : public COleDispatchDriver
{
public:
	CDownSamplingFunction() {}		// Calls COleDispatchDriver default constructor
	CDownSamplingFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDownSamplingFunction(const CDownSamplingFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetDownSampleMethod();
	void SetDownSampleMethod(long nNewValue);
	long GetTolerance();
	void SetTolerance(long nNewValue);
	long GetReducedSize();
};
