#if !defined(AFX_DRAGPOINTTOOL_H__1FA8FB98_636A_4FA0_B89D_A5BA4A51F88D__INCLUDED_)
#define AFX_DRAGPOINTTOOL_H__1FA8FB98_636A_4FA0_B89D_A5BA4A51F88D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDragPointTool wrapper class

class CDragPointTool : public COleDispatchDriver
{
public:
	CDragPointTool() {}		// Calls COleDispatchDriver default constructor
	CDragPointTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDragPointTool(const CDragPointTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	long GetDragStyle();
	void SetDragStyle(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DRAGPOINTTOOL_H__1FA8FB98_636A_4FA0_B89D_A5BA4A51F88D__INCLUDED_)
