// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEmbossFilter wrapper class

class CEmbossFilter : public COleDispatchDriver
{
public:
	CEmbossFilter() {}		// Calls COleDispatchDriver default constructor
	CEmbossFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CEmbossFilter(const CEmbossFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
