// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CExpMovAvgFunction wrapper class

class CExpMovAvgFunction : public COleDispatchDriver
{
public:
	CExpMovAvgFunction() {}		// Calls COleDispatchDriver default constructor
	CExpMovAvgFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CExpMovAvgFunction(const CExpMovAvgFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIgnoreNulls();
	void SetIgnoreNulls(BOOL bNewValue);
};
