#if !defined(AFX_FIBONACCIITEM_H__EB0355D7_388D_45A3_8CA7_7CFC7077A625__INCLUDED_)
#define AFX_FIBONACCIITEM_H__EB0355D7_388D_45A3_8CA7_7CFC7077A625__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CFibonacciItem wrapper class

class CFibonacciItem : public COleDispatchDriver
{
public:
	CFibonacciItem() {}		// Calls COleDispatchDriver default constructor
	CFibonacciItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFibonacciItem(const CFibonacciItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPen1 GetPen();
	double GetValue();
	void SetValue(double newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FIBONACCIITEM_H__EB0355D7_388D_45A3_8CA7_7CFC7077A625__INCLUDED_)
