// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CFilterRegion wrapper class

class CFilterRegion : public COleDispatchDriver
{
public:
	CFilterRegion() {}		// Calls COleDispatchDriver default constructor
	CFilterRegion(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFilterRegion(const CFilterRegion& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void SetRectangle(long Left, long Top, long Right, long Bottom);
	long GetHeight();
	void SetHeight(long nNewValue);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
};
