// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGrayScaleFilter wrapper class

class CGrayScaleFilter : public COleDispatchDriver
{
public:
	CGrayScaleFilter() {}		// Calls COleDispatchDriver default constructor
	CGrayScaleFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGrayScaleFilter(const CGrayScaleFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetMethod();
	void SetMethod(long nNewValue);
};
