// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueList;
class CPointer;

/////////////////////////////////////////////////////////////////////////////
// CHighLowLineSeries wrapper class

class CHighLowLineSeries : public COleDispatchDriver
{
public:
	CHighLowLineSeries() {}		// Calls COleDispatchDriver default constructor
	CHighLowLineSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHighLowLineSeries(const CHighLowLineSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long AddHighLow(double AX, double AHigh, double ALow, LPCTSTR AXLabel, unsigned long AColor);
	CValueList GetHighValues();
	CValueList GetLowValues();
	double MaxYValue();
	double MinYValue();
	CPointer GetHighPointer();
	CPointer GetLowPointer();
	long Clicked(long X, long Y);
};
