// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;
class CTeePicture;

/////////////////////////////////////////////////////////////////////////////
// CImagePointSeries wrapper class

class CImagePointSeries : public COleDispatchDriver
{
public:
	CImagePointSeries() {}		// Calls COleDispatchDriver default constructor
	CImagePointSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CImagePointSeries(const CImagePointSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPointer GetPointer();
	BOOL GetDark3D();
	void SetDark3D(BOOL bNewValue);
	long GetTransparency();
	void SetTransparency(long nNewValue);
	BOOL GetFastPoint();
	void SetFastPoint(BOOL bNewValue);
	long GetTreatNulls();
	void SetTreatNulls(long nNewValue);
	CTeePicture GetImagePoint();
	BOOL GetImageTransparent();
	void SetImageTransparent(BOOL bNewValue);
};
