// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueList;
class CPointer;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CKagiSeries wrapper class

class CKagiSeries : public COleDispatchDriver
{
public:
	CKagiSeries() {}		// Calls COleDispatchDriver default constructor
	CKagiSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CKagiSeries(const CKagiSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CValueList GetCloseValues();
	BOOL GetAbsoluteReversal();
	void SetAbsoluteReversal(BOOL bNewValue);
	CPointer GetBuySymbol();
	CPen1 GetDownSwing();
	double GetReversalAmount();
	void SetReversalAmount(double newValue);
	CPointer GetSellSymbol();
	CPen1 GetUpSwing();
};
