// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;
class CGradient;
class CTeeShadow;

/////////////////////////////////////////////////////////////////////////////
// CLegendSymbol wrapper class

class CLegendSymbol : public COleDispatchDriver
{
public:
	CLegendSymbol() {}		// Calls COleDispatchDriver default constructor
	CLegendSymbol(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLegendSymbol(const CLegendSymbol& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetContinuous();
	void SetContinuous(BOOL bNewValue);
	long GetPosition();
	void SetPosition(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetWidthUnits();
	void SetWidthUnits(long nNewValue);
	BOOL GetDefaultPen();
	void SetDefaultPen(BOOL bNewValue);
	CPen1 GetPen();
	BOOL GetSquared();
	void SetSquared(BOOL bNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	CGradient GetGradient();
	CTeeShadow GetShadow();
};
