// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLegendItem wrapper class

class CLegendItem : public COleDispatchDriver
{
public:
	CLegendItem() {}		// Calls COleDispatchDriver default constructor
	CLegendItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLegendItem(const CLegendItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	// method 'GetSymbolRect' not emitted because of invalid return type or parameter type
	// method 'SetSymbolRect' not emitted because of invalid return type or parameter type
	long GetAlign();
	long GetLeft();
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	long GetTop();
};
