// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeries;

/////////////////////////////////////////////////////////////////////////////
// CMACDFunction wrapper class

class CMACDFunction : public COleDispatchDriver
{
public:
	CMACDFunction() {}		// Calls COleDispatchDriver default constructor
	CMACDFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMACDFunction(const CMACDFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetPeriod2();
	void SetPeriod2(double newValue);
	CSeries GetMACDExp();
	CSeries GetHistogram();
	long GetPeriod3();
	void SetPeriod3(long nNewValue);
};
