// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMargins wrapper class

class CMargins : public COleDispatchDriver
{
public:
	CMargins() {}		// Calls COleDispatchDriver default constructor
	CMargins(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMargins(const CMargins& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	long GetRight();
	void SetRight(long nNewValue);
	long GetBottom();
	void SetBottom(long nNewValue);
	long GetUnits();
	void SetUnits(long nNewValue);
};
