// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CModeFunction wrapper class

class CModeFunction : public COleDispatchDriver
{
public:
	CModeFunction() {}		// Calls COleDispatchDriver default constructor
	CModeFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CModeFunction(const CModeFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIncludeNulls();
	void SetIncludeNulls(BOOL bNewValue);
};
