// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMosaicFilter wrapper class

class CMosaicFilter : public COleDispatchDriver
{
public:
	CMosaicFilter() {}		// Calls COleDispatchDriver default constructor
	CMosaicFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMosaicFilter(const CMosaicFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetPercent();
	void SetPercent(BOOL bNewValue);
	long GetAmount();
	void SetAmount(long nNewValue);
};
