// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPerformanceFunction wrapper class

class CPerformanceFunction : public COleDispatchDriver
{
public:
	CPerformanceFunction() {}		// Calls COleDispatchDriver default constructor
	CPerformanceFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPerformanceFunction(const CPerformanceFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double Calculate(long SourceSeriesIndex, long FirstIndex, long LastIndex);
};
