// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CLegend;

/////////////////////////////////////////////////////////////////////////////
// CPieOtherSlice wrapper class

class CPieOtherSlice : public COleDispatchDriver
{
public:
	CPieOtherSlice() {}		// Calls COleDispatchDriver default constructor
	CPieOtherSlice(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPieOtherSlice(const CPieOtherSlice& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStyle();
	void SetStyle(long nNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	double GetValue();
	void SetValue(double newValue);
	CLegend GetLegend();
};
