// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePoint2D;

/////////////////////////////////////////////////////////////////////////////
// CPointArray wrapper class

class CPointArray : public COleDispatchDriver
{
public:
	CPointArray() {}		// Calls COleDispatchDriver default constructor
	CPointArray(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPointArray(const CPointArray& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CTeePoint2D GetItem(long Index);
};
