// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPyramidSeries wrapper class

class CPyramidSeries : public COleDispatchDriver
{
public:
	CPyramidSeries() {}		// Calls COleDispatchDriver default constructor
	CPyramidSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPyramidSeries(const CPyramidSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetSizePercent();
	void SetSizePercent(long nNewValue);
};
