#if !defined(AFX_SERIESTEXTFIELDS_H__01067DA0_F2A4_4A61_BFD9_850B46F24D48__INCLUDED_)
#define AFX_SERIESTEXTFIELDS_H__01067DA0_F2A4_4A61_BFD9_850B46F24D48__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeriesTextField;

/////////////////////////////////////////////////////////////////////////////
// CSeriesTextFields wrapper class

class CSeriesTextFields : public COleDispatchDriver
{
public:
	CSeriesTextFields() {}		// Calls COleDispatchDriver default constructor
	CSeriesTextFields(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSeriesTextFields(const CSeriesTextFields& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CSeriesTextField GetItems(long Index);
	void Clear();
	void Delete(long Index);
	long GetCount();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SERIESTEXTFIELDS_H__01067DA0_F2A4_4A61_BFD9_850B46F24D48__INCLUDED_)
