// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCustomSeriesList;

/////////////////////////////////////////////////////////////////////////////
// CSeriesGroup wrapper class

class CSeriesGroup : public COleDispatchDriver
{
public:
	CSeriesGroup() {}		// Calls COleDispatchDriver default constructor
	CSeriesGroup(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSeriesGroup(const CSeriesGroup& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Add(long SeriesIndex);
	void Hide();
	void Show();
	long GetActive();
	void SetActive(long nNewValue);
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	VARIANT GetSeriesCount();
	long GetGroupLink();
	void Delete(long Index);
	void Insert(long IndexInGroup, long SeriesIndex);
	CCustomSeriesList GetSeries();
};
