#if !defined(AFX_SERIESXMLSOURCE_H__4935D4D3_8D00_4FB3_A6F8_A8E73011B7B1__INCLUDED_)
#define AFX_SERIESXMLSOURCE_H__4935D4D3_8D00_4FB3_A6F8_A8E73011B7B1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CStrings;

/////////////////////////////////////////////////////////////////////////////
// CSeriesXMLSource wrapper class

class CSeriesXMLSource : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSeriesXMLSource)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x17d6df37, 0xec2a, 0x45cd, { 0x8f, 0xd6, 0x33, 0x6d, 0x98, 0x33, 0xf8, 0x2d } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void Open();
	void Close();
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	void Load();
	void LoadFromFile(LPCTSTR FileName);
	void LoadFromURL(LPCTSTR URL);
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	long GetLoadMode();
	void SetLoadMode(long nNewValue);
	CString GetSeriesNode();
	void SetSeriesNode(LPCTSTR lpszNewValue);
	CString GetValueSource();
	void SetValueSource(LPCTSTR lpszNewValue);
	CStrings GetXml();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SERIESXMLSOURCE_H__4935D4D3_8D00_4FB3_A6F8_A8E73011B7B1__INCLUDED_)
