// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeriesMarkPosition;

/////////////////////////////////////////////////////////////////////////////
// CSeriesMarksPositions wrapper class

class CSeriesMarksPositions : public COleDispatchDriver
{
public:
	CSeriesMarksPositions() {}		// Calls COleDispatchDriver default constructor
	CSeriesMarksPositions(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSeriesMarksPositions(const CSeriesMarksPositions& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CSeriesMarkPosition GetPosition(long Index);
	void Automatic(long Index);
};
