// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSharpenFilter wrapper class

class CSharpenFilter : public COleDispatchDriver
{
public:
	CSharpenFilter() {}		// Calls COleDispatchDriver default constructor
	CSharpenFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSharpenFilter(const CSharpenFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
