// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSmoothingFunction wrapper class

class CSmoothingFunction : public COleDispatchDriver
{
public:
	CSmoothingFunction() {}		// Calls COleDispatchDriver default constructor
	CSmoothingFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSmoothingFunction(const CSmoothingFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetInterpolate();
	void SetInterpolate(BOOL bNewValue);
	long GetFactor();
	void SetFactor(long nNewValue);
};
