// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSoftenFilter wrapper class

class CSoftenFilter : public COleDispatchDriver
{
public:
	CSoftenFilter() {}		// Calls COleDispatchDriver default constructor
	CSoftenFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSoftenFilter(const CSoftenFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
