// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSpacing wrapper class

class CSpacing : public COleDispatchDriver
{
public:
	CSpacing() {}		// Calls COleDispatchDriver default constructor
	CSpacing(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSpacing(const CSpacing& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetHorizontal();
	void SetHorizontal(long nNewValue);
	long GetVertical();
	void SetVertical(long nNewValue);
};
