// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CSurfaceSides wrapper class

class CSurfaceSides : public COleDispatchDriver
{
public:
	CSurfaceSides() {}		// Calls COleDispatchDriver default constructor
	CSurfaceSides(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSurfaceSides(const CSurfaceSides& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CBrush1 GetBrush();
	BOOL GetLevels();
	void SetLevels(BOOL bNewValue);
	CPen1 GetPen();
};
