#if !defined(AFX_TEECOMMANDERBUTTON_H__E988FA80_4142_45CC_96E7_7131F0920FCD__INCLUDED_)
#define AFX_TEECOMMANDERBUTTON_H__E988FA80_4142_45CC_96E7_7131F0920FCD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeCommanderButton wrapper class

class CTeeCommanderButton : public COleDispatchDriver
{
public:
	CTeeCommanderButton() {}		// Calls COleDispatchDriver default constructor
	CTeeCommanderButton(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeCommanderButton(const CTeeCommanderButton& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Hide();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEECOMMANDERBUTTON_H__E988FA80_4142_45CC_96E7_7131F0920FCD__INCLUDED_)
