#if !defined(AFX_TEEEDITOR_H__E61EEAB6_4639_4590_8758_00C856713126__INCLUDED_)
#define AFX_TEEEDITOR_H__E61EEAB6_4639_4590_8758_00C856713126__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeEditorShowPages;
class CTeeEditorOptions;

/////////////////////////////////////////////////////////////////////////////
// CTeeEditor wrapper class

class CTeeEditor : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeeEditor)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xdae41fb8, 0x1815, 0x4f01, { 0xa7, 0xa1, 0x6c, 0x25, 0x17, 0xf6, 0xdc, 0xdb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	CString GetEditorTitle();
	void SetEditorTitle(LPCTSTR lpszNewValue);
	long GetDefaultPage();
	void SetDefaultPage(long nNewValue);
	void ShowEditor();
	BOOL GetAutoRepaint();
	void SetAutoRepaint(BOOL bNewValue);
	CTeeEditorShowPages GetShowPages();
	long GetEditorLink();
	CTeeEditorOptions GetOptions();
	BOOL GetTreeView();
	void SetTreeView(BOOL bNewValue);
	BOOL GetHighLightTabs();
	void SetHighLightTabs(BOOL bNewValue);
	long GetPixelsPerInch();
	void SetPixelsPerInch(long nNewValue);
	BOOL GetRememberPosition();
	void SetRememberPosition(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEEDITOR_H__E61EEAB6_4639_4590_8758_00C856713126__INCLUDED_)
