// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CFilterItems;

/////////////////////////////////////////////////////////////////////////////
// CTeePicture wrapper class

class CTeePicture : public COleDispatchDriver
{
public:
	CTeePicture() {}		// Calls COleDispatchDriver default constructor
	CTeePicture(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeePicture(const CTeePicture& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CFilterItems GetFilters();
	void LoadImage(LPCTSTR FileName);
	void AssignImage(long ImageHandle);
	void ClearImage();
	BOOL ShowFiltersEditor();
	long GetHandle();
	void SaveToFile(LPCTSTR FileName);
};
