#if !defined(AFX_TEEPREVIEWPANEL_H__D4D1C68A_DE5D_4E03_9E50_3A699E3A220E__INCLUDED_)
#define AFX_TEEPREVIEWPANEL_H__D4D1C68A_DE5D_4E03_9E50_3A699E3A220E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePanelsList;
class CGradient;
class CPen1;
class CCanvas;
class CTeeRect;

/////////////////////////////////////////////////////////////////////////////
// CTeePreviewPanel wrapper class

class CTeePreviewPanel : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeePreviewPanel)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x232856bb, 0x8228, 0x4047, { 0x84, 0xd6, 0xd2, 0x68, 0xfb, 0xe7, 0xdf, 0x27 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	BOOL GetAllowResize();
	void SetAllowResize(BOOL bNewValue);
	BOOL GetAllowMove();
	void SetAllowMove(BOOL bNewValue);
	BOOL GetAsBitmap();
	void SetAsBitmap(BOOL bNewValue);
	BOOL GetDragImage();
	void SetDragImage(BOOL bNewValue);
	long GetOrientation();
	void SetOrientation(long nNewValue);
	unsigned long GetPaperColor();
	void SetPaperColor(unsigned long newValue);
	unsigned long GetShadowColor();
	void SetShadowColor(unsigned long newValue);
	long GetShadowSize();
	void SetShadowSize(long nNewValue);
	BOOL GetShowImage();
	void SetShowImage(BOOL bNewValue);
	CString GetTitle();
	void SetTitle(LPCTSTR lpszNewValue);
	void Repaint();
	CTeePanelsList GetPanels();
	void AddChart(LPDISPATCH Value);
	CGradient GetGradient();
	CPen1 GetMargins();
	void PrintPage();
	void AddChartLink(long Value);
	CCanvas GetCanvas();
	CTeeRect GetPaperRect();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEPREVIEWPANEL_H__D4D1C68A_DE5D_4E03_9E50_3A699E3A220E__INCLUDED_)
