#if !defined(AFX_TEEPREVIEWER_H__D50160C7_03C3_44B8_9A95_6039315A6B9C__INCLUDED_)
#define AFX_TEEPREVIEWER_H__D50160C7_03C3_44B8_9A95_6039315A6B9C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePreviewerOptions;

/////////////////////////////////////////////////////////////////////////////
// CTeePreviewer wrapper class

class CTeePreviewer : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeePreviewer)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xb0fbb8bb, 0x8bb1, 0x4811, { 0x8e, 0x6, 0x70, 0x94, 0xbb, 0x2, 0xea, 0x72 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	CString GetPreviewTitle();
	void SetPreviewTitle(LPCTSTR lpszNewValue);
	void ShowPreview();
	unsigned long GetPaperColor();
	void SetPaperColor(unsigned long newValue);
	long GetPreviewerLink();
	BOOL GetMaximized();
	void SetMaximized(BOOL bNewValue);
	CTeePreviewerOptions GetOptions();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEPREVIEWER_H__D50160C7_03C3_44B8_9A95_6039315A6B9C__INCLUDED_)
