#if !defined(AFX_TRANSPOSESERIESTOOL_H__3C32B759_AFA8_4451_AFC9_EF79A18E16AA__INCLUDED_)
#define AFX_TRANSPOSESERIESTOOL_H__3C32B759_AFA8_4451_AFC9_EF79A18E16AA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTransposeSeriesTool wrapper class

class CTransposeSeriesTool : public COleDispatchDriver
{
public:
	CTransposeSeriesTool() {}		// Calls COleDispatchDriver default constructor
	CTransposeSeriesTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTransposeSeriesTool(const CTransposeSeriesTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Transpose();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TRANSPOSESERIESTOOL_H__3C32B759_AFA8_4451_AFC9_EF79A18E16AA__INCLUDED_)
