// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTrendFunction wrapper class

class CTrendFunction : public COleDispatchDriver
{
public:
	CTrendFunction() {}		// Calls COleDispatchDriver default constructor
	CTrendFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTrendFunction(const CTrendFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long CalculateTrend(double* m, double* b, long SourceSeriesIndex, long FirstIndex, long LastIndex);
};
