// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueList;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CVolumeSeries wrapper class

class CVolumeSeries : public COleDispatchDriver
{
public:
	CVolumeSeries() {}		// Calls COleDispatchDriver default constructor
	CVolumeSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVolumeSeries(const CVolumeSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CValueList GetVolumeValues();
	CPen1 GetLinePen();
	BOOL GetUseYOrigin();
	void SetUseYOrigin(BOOL bNewValue);
	double GetYOrigin();
	void SetYOrigin(double newValue);
};
